"use client";

import { FormEvent, useEffect, useState } from "react";
import type { Location } from "@/lib/types";
import { createPlace, deletePlace, getPlaces, type PlaceInput, updatePlace } from "@/lib/places";

const empty: PlaceInput = { name: "", description: "", category: "Ecotourism", lat: 11.25, lng: 75.78, region: "Kerala", capacity_max: 50, status: "active" };

export default function AdminPlacesPage() {
  const [places, setPlaces] = useState<Location[]>([]); const [form, setForm] = useState<PlaceInput>(empty); const [editing, setEditing] = useState<string | null>(null); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  const load = async () => { try { setPlaces(await getPlaces(true)); } catch (e) { setError(e instanceof Error ? e.message : "Unable to load places."); } };
  useEffect(() => { load(); }, []);
  const submit = async (event: FormEvent) => { event.preventDefault(); setSaving(true); setError(""); try { if (editing) await updatePlace(editing, form); else await createPlace(form); setForm(empty); setEditing(null); await load(); } catch (e) { setError(e instanceof Error ? e.message : "Unable to save place."); } finally { setSaving(false); } };
  const edit = (place: Location) => { setEditing(place.id); setForm({ name: place.name, description: place.description || "", category: place.category || "Ecotourism", lat: place.lat, lng: place.lng, region: place.region || "Kerala", capacity_max: place.capacity_max || 50, status: place.status || (place.is_active === false ? "hidden" : "active") }); };
  return <div style={{ maxWidth: 1180, margin: "0 auto" }}><header style={{ marginBottom: 24 }}><p style={{ color: "#4EDEA3", fontSize: 12, fontWeight: 700 }}>DESTINATION DIRECTORY</p><h1 style={{ margin: 0 }}>Places Manager</h1><p style={{ color: "#94A3B8" }}>Create, update, hide, or delete destinations used by every tourist discovery surface.</p></header>
    <div style={{ display: "grid", gridTemplateColumns: "minmax(310px, .8fr) 1.4fr", gap: 24 }}><form onSubmit={submit} style={{ background: "#111820", padding: 20, borderRadius: 14, display: "grid", gap: 12 }}><h2 style={{ margin: 0 }}>{editing ? "Edit place" : "New place"}</h2><label>Name<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} /></label><label>Category<input value={form.category} onChange={e=>setForm({...form,category:e.target.value})} /></label><label>Latitude<input type="number" value={form.lat} onChange={e=>setForm({...form,lat:Number(e.target.value)})} /></label><label>Longitude<input type="number" value={form.lng} onChange={e=>setForm({...form,lng:Number(e.target.value)})} /></label><label>Status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value as "active"|"hidden"})}><option value="active">Active</option><option value="hidden">Hidden</option></select></label><label>Description<textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})} /></label>{error && <p style={{color:"#f87171"}}>{error}</p>}<button disabled={saving}>{saving ? "Saving…" : editing ? "Save changes" : "Create place"}</button>{editing && <button type="button" onClick={()=>{setEditing(null);setForm(empty)}}>Cancel</button>}</form>
    <section style={{ background:"#111820", padding:20, borderRadius:14 }}><h2 style={{marginTop:0}}>All places ({places.length})</h2><table style={{width:"100%",borderCollapse:"collapse"}}><thead><tr style={{textAlign:"left",color:"#94A3B8"}}><th>Name</th><th>Category</th><th>Status</th><th>Coordinates</th><th /></tr></thead><tbody>{places.map(place=><tr key={place.id} style={{borderTop:"1px solid #243141"}}><td style={{padding:"12px 4px"}}><strong>{place.name}</strong><br/><small style={{color:"#94A3B8"}}>{place.region}</small></td><td>{place.category}</td><td>{place.status || (place.is_active === false ? "hidden" : "active")}</td><td>{Number(place.lat).toFixed(3)}, {Number(place.lng).toFixed(3)}</td><td style={{display:"flex",gap:8,padding:"12px 0"}}><button onClick={()=>edit(place)}>Edit</button><button onClick={async()=>{if(confirm(`Delete ${place.name}?`)){try{await deletePlace(place.id);await load()}catch(e){setError(e instanceof Error?e.message:"Unable to delete place.")}}}} style={{color:"#f87171"}}>Delete</button></td></tr>)}</tbody></table></section></div></div>;
}
